### ISSUE TITLE
请问，目前这个工程是否可以运行呢？

### ISSUE THREAD

**Issue by lwlizhe** [Rabtman/AcgClub#10]
我下载编译完成之后，发现编译失败，依赖缺失（不是dagger生成那些）……
例如：
com.rabtman.acgclub.di.component.AcgPicComponent 
中的
com.rabtman.acgclub.mvp.ui.fragment.APicFragment
并不存在……

**Comment by Rabtman** [comment]
更新一下，现在没问题了；想运行的话一般从tag去下载，主线更新有时候不注意会漏提交东西

**Comment by lwlizhe** [comment]
OK，了解了，非常感谢
