### ISSUE TITLE
gradle assembleRelease不通过啊

### ISSUE THREAD

**Issue by dacheng2014** [Rabtman/AcgClub#13]
w: 注: ARouter::Compiler >>> AutowiredProcessor init. <<<
w: 警告: 来自注释处理程序 'org.jetbrains.kotlin.kapt3.ProcessorWrapper' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
e: 错误: ARouter::Compiler An exception is encountered, [These no module name, at 'build.gradle', like :
  apt {
      arguments {
          moduleName project.getName();
      }
  }
  ]

 What went wrong:
Execution failed for task ':component-acgcomic:kaptReleaseKotlin'.
> Compilation error. See log for more details

打包上面 RELEASE_7' 低于 -source '1.8   出错了  怎么解决啊 ？

**Comment by Rabtman** [comment]
编译是没问题的，那行只是警告，错误原因应该是你的编译环境问题，或者你进行了改动，具体请结合搜索引擎查看问题。
