### ISSUE TITLE
使用android studio 打开，无法运行，库无法引入成功

### ISSUE THREAD

**Issue by cornucopib** [Rabtman/AcgClub#2]
Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.aliyun.ams:alicloud-android-utils:1.0.3.

**Comment by Rabtman** [comment]
应该是阿里远程库的问题，你可以按文档把这个库改成手动引入，https://help.aliyun.com/document_detail/53144.html
