### ISSUE TITLE
第一次编译

### ISSUE THREAD

**Issue by DreamClimb** [Rabtman/AcgClub#4]
Error:(87, 0) path may not be null or empty string. path='null'

signingConfigs {
        rabtman {
            storeFile file(properties.getProperty("storeFile"))
            storePassword properties.getProperty("storePassword")
            keyAlias properties.getProperty("keyAlias")
            keyPassword properties.getProperty("keyPassword")
        }
    }

这里面的路径

**Comment by Rabtman** [comment]
readme写了，自己在本地配置签名文件或者去掉
