### ISSUE TITLE
大家好。有没有人遇到阿里云相关包没办法导入的问题？如何解决？

### ISSUE THREAD

**Issue by ShshyDevooo** [Rabtman/AcgClub#5]
如题，在build的时候
![ahg0 dvximg r 7p50g s8](https://user-images.githubusercontent.com/9620338/40592574-af104a88-6253-11e8-8c1d-b8d54d7d2af3.png)

**Comment by ShshyDevooo** [comment]
![tim 20180528093004](https://user-images.githubusercontent.com/9620338/40593238-b5bf11a6-6259-11e8-91fb-c2f6704ba666.png)

**Comment by Rabtman** [comment]
改用阿里云移动用户反馈最新集成方式即可

**Comment by ShshyDevooo** [comment]
你好，是按照官网上的集成方式集成么，还是出现一样的问题啊？

**Comment by ShshyDevooo** [comment]
大家好，真正的问题出现在gradle.properties，注释掉下面两行就可以了。
![tim 20180529092154](https://user-images.githubusercontent.com/9620338/40633356-d7435eea-6321-11e8-95d0-760e853a9ed3.png)
